---
- name: Initialize cloud image
  hosts: virtualmachines
  remote_user: ikuinenpadawan
  become: true

  tasks:
    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes

    - name: Change SSH Port
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^Port 22'
        line="Port 1234"
        state=present
        backup=yes

    - name: Allow SSH access to selected users
      lineinfile:
        dest=/etc/ssh/sshd_config
        line="AllowUsers ikuinenpadawan"
        create=yes
    
    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted


